/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAddonsRouteImport } from './routes/_app/addons'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppArtifactsRouteImport } from './routes/_app/artifacts'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppCronRouteImport } from './routes/_app/cron'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppMemoryRouteImport } from './routes/_app/memory'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as ApiAuthMethodsRouteImport } from './routes/api/auth-methods'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHermesRouteImport } from './routes/api/hermes'
import { Route as ApiPhoneRouteImport } from './routes/api/phone'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as AuthCompleteRouteImport } from './routes/auth/complete'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddonsRoute = AppAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppArtifactsRoute = AppArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppCronRoute = AppCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthMethodsRoute = ApiAuthMethodsRouteImport.update({
  id: '/api/auth-methods',
  path: '/api/auth-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesRoute = ApiHermesRouteImport.update({
  id: '/api/hermes',
  path: '/api/hermes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhoneRoute = ApiPhoneRouteImport.update({
  id: '/api/phone',
  path: '/api/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCompleteRoute = AuthCompleteRouteImport.update({
  id: '/auth/complete',
  path: '/auth/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/addons': typeof AppAddonsRoute
  '/agents': typeof AppAgentsRoute
  '/artifacts': typeof AppArtifactsRoute
  '/connect': typeof AppConnectRoute
  '/cron': typeof AppCronRoute
  '/insights': typeof AppInsightsRoute
  '/memory': typeof AppMemoryRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/tools': typeof AppToolsRoute
  '/api/auth-methods': typeof ApiAuthMethodsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hermes': typeof ApiHermesRoute
  '/api/phone': typeof ApiPhoneRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/addons': typeof AppAddonsRoute
  '/agents': typeof AppAgentsRoute
  '/artifacts': typeof AppArtifactsRoute
  '/connect': typeof AppConnectRoute
  '/cron': typeof AppCronRoute
  '/insights': typeof AppInsightsRoute
  '/memory': typeof AppMemoryRoute
  '/projects': typeof AppProjectsRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/tools': typeof AppToolsRoute
  '/api/auth-methods': typeof ApiAuthMethodsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hermes': typeof ApiHermesRoute
  '/api/phone': typeof ApiPhoneRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/addons': typeof AppAddonsRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/artifacts': typeof AppArtifactsRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/cron': typeof AppCronRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/tools': typeof AppToolsRoute
  '/api/auth-methods': typeof ApiAuthMethodsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/hermes': typeof ApiHermesRoute
  '/api/phone': typeof ApiPhoneRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/auth/complete': typeof AuthCompleteRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/addons'
    | '/agents'
    | '/artifacts'
    | '/connect'
    | '/cron'
    | '/insights'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tools'
    | '/api/auth-methods'
    | '/api/chat'
    | '/api/hermes'
    | '/api/phone'
    | '/api/status'
    | '/api/sync'
    | '/api/telemetry'
    | '/auth/complete'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/addons'
    | '/agents'
    | '/artifacts'
    | '/connect'
    | '/cron'
    | '/insights'
    | '/memory'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/tools'
    | '/api/auth-methods'
    | '/api/chat'
    | '/api/hermes'
    | '/api/phone'
    | '/api/status'
    | '/api/sync'
    | '/api/telemetry'
    | '/auth/complete'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/addons'
    | '/_app/agents'
    | '/_app/artifacts'
    | '/_app/connect'
    | '/_app/cron'
    | '/_app/insights'
    | '/_app/memory'
    | '/_app/projects'
    | '/_app/settings'
    | '/_app/skills'
    | '/_app/tools'
    | '/api/auth-methods'
    | '/api/chat'
    | '/api/hermes'
    | '/api/phone'
    | '/api/status'
    | '/api/sync'
    | '/api/telemetry'
    | '/auth/complete'
    | '/_app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthMethodsRoute: typeof ApiAuthMethodsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHermesRoute: typeof ApiHermesRoute
  ApiPhoneRoute: typeof ApiPhoneRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  AuthCompleteRoute: typeof AuthCompleteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/addons': {
      id: '/_app/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AppAddonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artifacts': {
      id: '/_app/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof AppArtifactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cron': {
      id: '/_app/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof AppCronRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth-methods': {
      id: '/api/auth-methods'
      path: '/api/auth-methods'
      fullPath: '/api/auth-methods'
      preLoaderRoute: typeof ApiAuthMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes': {
      id: '/api/hermes'
      path: '/api/hermes'
      fullPath: '/api/hermes'
      preLoaderRoute: typeof ApiHermesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phone': {
      id: '/api/phone'
      path: '/api/phone'
      fullPath: '/api/phone'
      preLoaderRoute: typeof ApiPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/complete': {
      id: '/auth/complete'
      path: '/auth/complete'
      fullPath: '/auth/complete'
      preLoaderRoute: typeof AuthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAddonsRoute: typeof AppAddonsRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppArtifactsRoute: typeof AppArtifactsRoute
  AppConnectRoute: typeof AppConnectRoute
  AppCronRoute: typeof AppCronRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppToolsRoute: typeof AppToolsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddonsRoute: AppAddonsRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppArtifactsRoute: AppArtifactsRoute,
  AppConnectRoute: AppConnectRoute,
  AppCronRoute: AppCronRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppToolsRoute: AppToolsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthMethodsRoute: ApiAuthMethodsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHermesRoute: ApiHermesRoute,
  ApiPhoneRoute: ApiPhoneRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  AuthCompleteRoute: AuthCompleteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
